<a href="https://colab.research.google.com/github/VinothaManas/Resume/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


Creating Tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8, 10],
                       [9, 10, 11]])
MATRIX

tensor([[ 7,  8, 10],
        [ 9, 10, 11]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([ 7,  8, 10])

In [ ]:
MATRIX[1]

tensor([ 9, 10, 11])

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [3, 7, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 7, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1]

tensor([[1, 2, 3],
        [3, 7, 9],
        [2, 4, 5]])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3, 6],
                        [3, 6, 9, 10],
                        [2, 4, 5, 11],
                        [3, 6, 9, 10]],
                       [[1, 2, 3, 4],
                        [3, 7, 9, 12],
                        [2, 4, 5, 15],
                        [3, 6, 9, 10]]])
TENSOR.shape

torch.Size([2, 4, 4])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that
they start with tensors ful lof random numbers and then adjust those random numbers
to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4981, 0.8531, 0.4047, 0.4127],
        [0.8040, 0.1181, 0.4541, 0.3244],
        [0.6442, 0.5982, 0.2350, 0.5809]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [ ]:
# Creating a tensor of all zeros
zeros = torch.zeros(size = (2, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Creating a tensor of all ones
ones = torch.ones(size = (3, 7))
ones.dtype

torch.float32

In [ ]:
# Using torch.range()
one_to_ten1 = torch.range(1, 11)
one_to_ten1

<ipython-input-68-d075374c9d38>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten1 = torch.range(1, 11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
# Using torch.arange()
one_to_ten2 = torch.arange(1, 11)
one_to_ten2

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten3 = torch.arange(start=1, end=11, step=2)
one_to_ten3

tensor([1, 3, 5, 7, 9])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten2)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device



In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, #what datatype is the tensor (e.g. float32 or float16)
                               device = None, #what device is your tensor on
                               requires_grad = False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype = torch.int32)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a sensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`



In [ ]:
#Creating a tensor
some_tensor = torch.rand([3, 5])
some_tensor

tensor([[0.7063, 0.3865, 0.0644, 0.8075, 0.2186],
        [0.0031, 0.8381, 0.7829, 0.1560, 0.6977],
        [0.2490, 0.7887, 0.9114, 0.6104, 0.8504]])

In [ ]:
some_tensor.size(), some_tensor.shape  #both are same expect that size is a method and shape is an attribute

(torch.Size([3, 5]), torch.Size([3, 5]))

In [ ]:
# Finding out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7063, 0.3865, 0.0644, 0.8075, 0.2186],
        [0.0031, 0.8381, 0.7829, 0.1560, 0.6977],
        [0.2490, 0.7887, 0.9114, 0.6104, 0.8504]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 5])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Creating a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Multiplying tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)
tensor

tensor([1, 2, 3])

In [ ]:
tensor = torch.add(tensor, 10)
tensor

tensor([20, 30, 40])

### Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
# Element-wise multiplication
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.49 ms, sys: 33 µs, total: 2.52 ms
Wall time: 4.07 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.84 ms, sys: 0 ns, total: 1.84 ms
Wall time: 6.87 ms


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
torch.matmul(torch.rand(2, 2), torch.rand(2, 3))

tensor([[0.1556, 0.7906, 0.4313],
        [0.7008, 1.1070, 1.1507]])